/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starbucksemulator;

import java.awt.FontMetrics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import javax.swing.JTabbedPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.plaf.basic.BasicTabbedPaneUI;

/**
 *
 * @author shirdav18
 */
public class EmulatorPanel extends javax.swing.JPanel {

    private Statement stmt;
    
    public EmulatorPanel(Statement s) {
        initComponents();
        stmt = s;
        labelTabs.setTabPlacement(JTabbedPane.RIGHT);
        labelTabs.setUI(new BasicTabbedPaneUI() {
            @Override
            protected int calculateTabWidth(
                    int tabPlacement, int tabIndex, FontMetrics metrics) {
                return 100;
            }
            
            @Override
            protected int calculateTabHeight(
                    int tabPlacement, int tabIndex, int fontHeight) {
                return 119;
            }
        });
        MainScreen ms = new MainScreen();
        labelTabs.addTab("MAIN", null, ms, null);
        SyrupScreen ss = new SyrupScreen();
        labelTabs.addTab("SYRUP", null, ss, null);
        MilkScreen m2s = new MilkScreen(stmt);
        labelTabs.addTab("MILK", null, m2s, null);
        CustomScreen cs = new CustomScreen();
        labelTabs.addTab("CUSTOM", null, cs, null);
        EspressoDrinkScreen eds = new EspressoDrinkScreen(stmt);
        labelTabs.addTab("ESPRESSO", null, eds, null);
        labelTabs.setVisible(true);
        labelTabs.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        itemDisplay.setEditable(false);
        itemDisplay.setText("");
        itemDisplay.setLineWrap(true);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        updateText(StarbucksEmulator.order.toString());
    }
    
    public void updateText(String s) {
        itemDisplay.setText(s);
        priceBtn.setText(String.format("%.2f", StarbucksEmulator.order.getCost()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTabs = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemDisplay = new javax.swing.JTextArea();
        voidItemBtn = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        priceBtn = new javax.swing.JButton();

        itemDisplay.setColumns(20);
        itemDisplay.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        itemDisplay.setRows(5);
        jScrollPane1.setViewportView(itemDisplay);

        voidItemBtn.setBackground(new java.awt.Color(204, 255, 255));
        voidItemBtn.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        voidItemBtn.setText("Void Item");
        voidItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voidItemBtnMouseClicked(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("TOTAL");

        priceBtn.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        priceBtn.setText("[price]");
        priceBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        priceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(voidItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voidItemBtn)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(priceBtn)))
                    .addComponent(labelTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void voidItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voidItemBtnMouseClicked
        Item i = StarbucksEmulator.order.current();
        if (i != null && i instanceof Drink) {
            ((Drink)i).removeCustom();
            updateText(StarbucksEmulator.order.toString());
        }
    }//GEN-LAST:event_voidItemBtnMouseClicked

    private void priceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceBtnMouseClicked
        DataMover dm = StarbucksEmulator.dm;
        Thread thread = new Thread() {
            public void run() {
                TextInfo ti = new TextInfo(dm);
                ti.setVisible(true);
                dm.guardDone();
                ti.dispose();
                StarbucksEmulator.order.name = dm.getString();
                System.out.println(StarbucksEmulator.order);
                StarbucksEmulator.order = new Order();
            }
        };
        thread.start();
    }//GEN-LAST:event_priceBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea itemDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane labelTabs;
    private javax.swing.JButton priceBtn;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton voidItemBtn;
    // End of variables declaration//GEN-END:variables
}
